scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['servicea:8080']
      - targets: ['serviceb:8090']
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']